cursos/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('cursos.views',
            url(r'^$', 'cursos'),
            url(r'^(?P<slug>[\w_-]+)/$', 'curso'),
            url(r'^instrutor/(?P<slug>[\w_-]+)$', 'instrutor'),
            url(r'^inscricao/(?P<slug>[\w_-]+)$', 'inscricao'),
            url(r'^alunos/cadastro/$', 'cadastro'),
            url(r'^alunos/cadastrar/$', 'cadastrar'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import os
dir = os.path.abspath(os.path.dirname(__file__))

urlpatterns = patterns('',
    # Example:
    # (r'^join/', include('join.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    (r'^$', 'views.bemvindo'),
    (r'^cursos/', include('cursos.urls')),
    (r'^media/(.*)$', 'django.views.static.serve', { 'document_root' : settings.MEDIA_ROOT }),
    (r'^login/$', 'django.contrib.auth.views.login', { 'template_name' : 'login.html'}),
    (r'^logout/$', 'django.contrib.auth.views.logout', { 'template_name' : 'logout.html'}),
)

cursos/models.py
#coding:utf-8
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from util.signals import curso_pre_save, instrutor_pre_save, inscricao_post_save
from django.db.models import signals
from django.utils.translation import gettext_lazy

# Create your models here.
class Instrutor(models.Model):
    class Meta:
        ordering = ('nome',)
        verbose_name = gettext_lazy('Instrutor')
        verbose_name_plural = gettext_lazy('Instrutores')

    nome = models.CharField(max_length = 200)
    biografia = models.TextField()
    formacao = models.CharField(max_length = 250)
    foto = models.ImageField(
                    upload_to = 'cursos/fotos_instrutores'
                )
    slug = models.SlugField(max_length = 100, blank = True, unique = True)

    def get_url(self):
        return reverse('cursos.views.instrutor', kwargs = { 'slug' : self.slug })

    def __unicode__(self):
        return self.nome

class Curso(models.Model):
    class Meta:
        ordering = ('titulo',)
        verbose_name = gettext_lazy('Curso')
        verbose_name_plural = gettext_lazy('Cursos')

    titulo = models.CharField(max_length = 300)
    descricao = models.TextField()
    carga_horaria = models.IntegerField()
    vagas = models.IntegerField()
    inscricoes_abertas = models.BooleanField(verbose_name = 'Aceitando inscrições')
    instrutor = models.ForeignKey('Instrutor')
    pre_requisitos = models.TextField()
    slug = models.SlugField(max_length = 100, blank = True, unique = True)

    def get_url(self):
        return reverse('cursos.views.curso', kwargs = { 'slug' : self.slug })

    def get_url_inscricao(self):
        return reverse('cursos.views.inscricao', kwargs = { 'slug' : self.slug })

    def __unicode__(self):
        return self.titulo

class Aluno(User):
    class Meta:
        ordering = ('first_name', 'username',)
        verbose_name = gettext_lazy('Aluno')
        verbose_name_plural = gettext_lazy('Alunos')

    cpf = models.CharField(max_length = 11, unique = True)

    def __unicode__(self):
        return self.username

class Telefone(models.Model):
    class Meta:
        verbose_name = gettext_lazy('Telefone')
        verbose_name_plural = gettext_lazy('Telefones')

    ddd = models.CharField(max_length = 2)
    numero = models.CharField(max_length = 8)
    proprietario = models.ForeignKey('Aluno')

    def __unicode__(self):
        return '(%s) %s' % (self.ddd, self.numero)

class Inscricao(models.Model):
    class Meta:
        verbose_name = gettext_lazy('Inscrição')
        verbose_name_plural = gettext_lazy('Inscrições')

    status = models.BooleanField(verbose_name = 'Confirmada')
    data_inscricao = models.DateField()
    aluno = models.ForeignKey('Aluno')
    curso = models.ForeignKey('Curso')

# Conectando sinais
signals.pre_save.connect(instrutor_pre_save, sender = Instrutor)
signals.pre_save.connect(curso_pre_save, sender = Curso)
signals.post_save.connect(inscricao_post_save, sender = Inscricao)

cursos/forms.py
#coding:utf-8

from django import forms
from django.contrib.auth.models import User
from models import Aluno
from util.validacoes import validar_cpf

class AlunoForm(forms.ModelForm):
    class Meta:
        model = Aluno
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    cpf = forms.CharField(max_length = 15, widget = forms.TextInput())
    password = forms.CharField(max_length = 16, min_length = 4, widget = forms.PasswordInput, label = 'Senha')
    confirmacao_senha = forms.CharField(max_length = 16, min_length = 4, widget = forms.PasswordInput)
    email = forms.EmailField(max_length = 200, min_length = 6, label = 'E-mail', required = True)
    first_name = forms.CharField(max_length = 50, min_length = 3, required = True)
    last_name = forms.CharField(max_length = 100, min_length = 3, required = True)

    def clean_cpf(self):
        self.cleaned_data['cpf'] = self.cleaned_data['cpf'].replace('.', '').replace('-', '')
        if not validar_cpf(self.cleaned_data['cpf']):
            raise forms.ValidationError('Você deve digitar um CPF válido.')

        if Aluno.objects.filter(cpf = self.cleaned_data['cpf']).count() > 0:
            raise forms.ValidationError('Este CPF já está cadastrado.')

        return self.cleaned_data['cpf']

    def clean_username(self):
        if User.objects.filter(username = self.cleaned_data['username']).count() > 0:
            raise forms.ValidationError('Já existe um usuário com este login.')

        return self.cleaned_data['username']

    def clean_email(self):
        if User.objects.filter(email = self.cleaned_data['email']).count() > 0:
            raise forms.ValidationError('Já existe um usuário com este e-mail.')

        return self.cleaned_data['email']

    def clean_confirmacao_senha(self):
        if self.cleaned_data['confirmacao_senha'] != self.data['password']:
            raise forms.ValidationError('A senha e a confirmação da senha não correspondem.')

        return self.cleaned_data['confirmacao_senha']

    def save(self, commit = True):
        aluno = super(AlunoForm, self).save(commit = False)
        aluno.set_password(self.cleaned_data['password'])
        aluno.cpf = self.cleaned_data['cpf']

        if commit:
            aluno.save()

        return aluno

cursos/views.py
#coding:utf-8
# Create your views here.
from django.shortcuts import get_object_or_404
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from models import Instrutor, Curso
from forms import AlunoForm

def cursos(request):
    cursos = Curso.objects.all()
    return render_to_response('cursos.html', locals(), context_instance = RequestContext(request))

def cadastro(request):
    form = AlunoForm()
    return render_to_response('cadastro_aluno.html', locals(), context_instance = RequestContext(request))

def cadastrar(request):
    if request.method == 'POST':
        form = AlunoForm(request.POST)
        if form.is_valid():
            form.save()
            msg = 'Cadastro efetuado com sucesso!'

        return render_to_response('cadastro_aluno.html', locals(), context_instance = RequestContext(request))
    else:
        return HttpResponse('Esta página deve tratar um formulário, não acesse-a diretamente.')

@login_required
def instrutor(request, slug):
    instrutor = get_object_or_404(Instrutor, slug = slug)
    return render_to_response('instrutor.html', locals(), context_instance = RequestContext(request))

@login_required
def curso(request, slug):
    curso = get_object_or_404(Curso, slug = slug)
    return render_to_response('curso.html', locals(), context_instance = RequestContext(request))

@login_required
def inscricao(request, slug):
    curso = get_object_or_404(Curso, slug = slug)
    if not curso.inscricoes_abertas:
        erro = u'Este curso não está recebendo inscrições.'
    return render_to_response('inscricao.html', locals(), context_instance = RequestContext(request))

views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def bemvindo(request):
    return render_to_response('bemvindo.html', locals(), context_instance = RequestContext(request))

templates/bemvindo.html
{% extends "super.html" %}

{% block topo %}
    <h1>Seja bem-vindo!</h1>
{% endblock topo %}

{% block conteudo %}
    <p>Seja bem-vindo ao nosso sistema.</p>
    <p>Navegue pelo menu superior.</p>
{% endblock conteudo %} 

templates/cadastro_aluno.html
{% extends "super.html" %}

{% block titulo %}{{ block.super }} - Cadastro de aluno{% endblock titulo %}

{% block topo %}
    <div align="center"><h1>Cadastro de usuário</h1></div>
{% endblock topo %}

{% block conteudo %}
    {% if msg %}
        <strong>{{ msg }}</strong>
    {% else %}
        <form method="post" action="{% url cursos.views.cadastrar %}">
            <table class="table_form" cellpadding="2" cellspacing="0">
                <tr>
                    <td class="label_table_form">Nome:</td>
                    <td class="wid_table_form">{{ form.first_name }}
                    {% if form.first_name.errors %}
                        <br /><div class="erro">{{ form.first_name.errors }}</div>
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="label_table_form">Sobrenome:</td>
                    <td class="wid_table_form">{{ form.last_name }}
                    {% if form.last_name.errors %}
                        <br /><div class="erro">{{ form.last_name.errors }}</div>
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="label_table_form">E-mail:</td>
                    <td class="wid_table_form">{{ form.email }}
                    {% if form.email.errors %}
                        <br /><div class="erro">{{ form.email.errors }}</div>
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="label_table_form">Nome de usuário:</td>
                    <td class="wid_table_form">{{ form.username }}
                    {% if form.username.errors %}
                        <br /><div class="erro">{{ form.username.errors }}</div>
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="label_table_form">Senha:</td>
                    <td class="wid_table_form">{{ form.password }}
                    {% if form.password.errors %}
                        <br /><div class="erro">{{ form.password.errors }}</div>
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="label_table_form">Confirme a senha:</td>
                    <td class="wid_table_form">{{ form.confirmacao_senha }}
                    {% if form.confirmacao_senha.errors %}
                        <br /><div class="erro">{{ form.confirmacao_senha.errors }}</div>
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="label_table_form">CPF:</td>
                    <td class="wid_table_form">{{ form.cpf }}
                    {% if form.cpf.errors %}
                        <br /><div class="erro">{{ form.cpf.errors }}</div>
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="label_table_form">&nbsp;</td>
                    <td class="submit_table_form"><input type="submit" value="Cadastrar" /></td>
                </tr>
            </table>
        </form>
    {% endif %}
{% endblock conteudo %}

templates/curso.html
{% extends "super.html" %}

{% block titulo %}{{ block.super }} - Curso "{{ curso.titulo }}"{% endblock titulo %}

{% block topo %}
    <h1>{{ curso.titulo }}</h1>
{% endblock topo %}

{% block conteudo %}
    <p><strong>Instrutor:</strong> <a href="{{ curso.instrutor.get_url }}">{{ curso.instrutor.nome }}</a><br />
    <strong>Descrição do curso:</strong> {{ curso.descricao }}<br />
    <strong>Carga horária:</strong> {{ curso.carga_horaria }} horas<br />
    <strong>Pré-requisitos:</strong> {{ curso.pre_requisitos }}<br />
    <strong>Quantidade de vagas:</strong> {{ curso.vagas }}<br />
    <strong>Inscritos:</strong> {{ curso.inscricao_set.all.count }}</p>
    
    <p align="center">
    {% if curso.inscricoes_abertas %}
        <a href="{{ curso.get_url_inscricao }}">Inscrever-se</a> |
    {% endif %} <a href="{% url cursos.views.cursos %}">Voltar para a listagem de cursos</a></p>
{% endblock conteudo %}

templates/cursos.html
{% extends "super.html" %}

{% block titulo %}{{ block.super }} - Visualização dos Cursos{% endblock titulo %}

{% block topo %}
    <h1>Listagem de cursos</h1>
{% endblock topo %}

{% block conteudo %}
    <p>Veja abaixo uma lista de cursos. Para visualizar detalhes de um curso, clique sobre o mesmo.
    Você deve estar autenticado para visualizar os detalhes dos cursos.</p>
    {% if not cursos %}
        <p>Nenhum curso cadastrado.</p>
    {% endif %}
    <ul>
        {% for curso in cursos %}
            <li><a href="{{ curso.get_url }}">{{ curso.titulo }}</a> (instrutor: {{ curso.instrutor.nome }});</li>
        {% endfor %}
    </ul>
{% endblock conteudo %}

templates/inscricao.html
{% extends "super.html" %}

{% block titulo %}{{ block.super }} - Inscrição no Curso "{{ curso.titulo }}"{% endblock titulo %}

{% block topo %}
    <h1>
        {% if erro %}
            Erro!
        {% else %}
            Inscrição no curso "{{ curso.titulo }}"
        {% endif %}
    </h1>
{% endblock topo %}

{% block conteudo %}
    {% if erro %}
        <div class="mensagem_erro">{{ erro }}</div>
    {% else %}
        <p>Em construção.</p>
        <p align="center"><a href="javascript:history.back();">Voltar</a></p>
    {% endif %}
{% endblock conteudo %}

templates/instrutor.html
{% extends "super.html" %}

{% block titulo %}{{ block.super }} - Instrutor "{{ instrutor.nome }}"{% endblock titulo %}

{% block topo %}
    <h1>{{ instrutor.nome }}</h1>
{% endblock topo %}

{% block conteudo %}
    <p><img align="right" src="{{ MEDIA_URL }}{{ instrutor.foto }}" class="foto_instrutor" />
    <strong>Nome:</strong> {{ instrutor.nome }}<br />
    <strong>Biografia:</strong> {{ instrutor.biografia|linebreaks }}<br />
    <strong>Formação:</strong> {{ instrutor.formacao }}<br />
    </p>
    
    <p><strong>Cursos deste instrutor</strong></p>
    
    <ul>
        {% for curso in instrutor.curso_set.all %}
            <li><a href="{{ curso.get_url }}">{{ curso.titulo }}</a></li>
        {% endfor %}
    </ul>
    
    <p align="center"><a href="javascript:history.back();">Voltar</a></p>
{% endblock conteudo %}

templates/login.html
{% extends "super.html" %}

{% block titulo %}{{ block.super }} - Login{% endblock titulo %}

{% block scripts %}
    {{ block.super }}
    <script>
        function validarLogin(formulario) {
            if (formulario.username.value != "" && formulario.password.value != "") {
                return true;
            } else {
                alert("Preencha corretamente todos os campos.");
                formulario.username.focus();
                return false;
            }
        }
    </script>
{% endblock scripts %}

{% block topo %}
    <h1>Efetuar Login no Sistema</h1>
{% endblock topo %}

{% block conteudo %}
    {% if form.errors %}
        <div align="center" style="padding-top:1em;padding-bottom:2em;font-size:16px;color:red;">
            Erro: Usuario ou senha incorretos.
        </div>
    {% endif %}
    
    <form action="." name="login" id="formLogin" method="post" onsubmit="return validarLogin(this);">
        {% if next %}
            <div class="aviso">Você deve efetuar login para acessar esta área, caso não seja cadastrado, <a href="{% url cursos.views.cadastro %}">clique aqui e se cadastre</a>.</div>
        {% endif %}
        <div id="divLogin" align="right" class="divAfastada">
            Nome de usuário: {{ form.username }}<br />
            Senha: {{ form.password }}<br /><br />
            <input type="hidden" name="next" value="{{ next }}" />
            <input type="submit" value="Entrar" />
        </div>
    </form>
{% endblock conteudo %}

templates/logout.html
{% extends "super.html" %}

{% block topo %}
    <h1>Logout...</h1>
{% endblock topo %}

{% block conteudo %}
    <p>Você efetuou logout com sucesso.</p>
{% endblock conteudo %}

templates/super.html
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>{% block titulo %}Join - Gerenciador de Cursos{% endblock titulo %}</title>

{% block metatags %}
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Language" content="pt-br" />
<meta name="keywords" content="cursos, inscrição, estudos" />
<meta name="description" content="Join é um sistema de gerenciamento de inscrições em cursos." />
{% endblock metatags %} 

{% block style %} 
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}style.css" />
{% endblock style %} 

{% block scripts %} 

{% endblock scripts %}

</head>
<body>

    <div id="tudo">
        <div id="menu">
            {% block menu %}
                <a href="{% url views.bemvindo %}">Página Inicial</a> | 
                <a href="{% url cursos.views.cursos %}">Listagem de Cursos</a> | 
                {% if user.is_authenticated %}
                    <a href="{% url django.contrib.auth.views.logout %}">Sair do sistema</a> | 
                {% else %}
                    <a href="{% url django.contrib.auth.views.login %}">Entrar no sistema</a> |
                    <a href="{% url cursos.views.cadastro %}">Cadastrar-se</a> |  
                {% endif %}
                <a href="{% url views.bemvindo %}admin/" target="_blank">Administração</a>
            {% endblock menu %}
        </div>
        
        {% if user.is_authenticated %}
            <div id="mensagem_usuario">
                Seja-bem vindo, <strong>{{ user.first_name }} {{ user.last_name }}</strong>.
            </div>
        {% endif %}
        
        <div id="topo">
            {% block topo %}
            {% endblock topo %}
        </div>
        
        <div id="conteudo">
            {% block conteudo %}
            {% endblock conteudo %}
        </div>
        
        <div id="rodape">
            {% block rodape %}
                <a rel="license" target="_blank" href="http://creativecommons.org/licenses/by-nc-sa/2.5/br/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/2.5/br/88x31.png" /></a><br /><span xmlns:dc="http://purl.org/dc/elements/1.1/" href="http://purl.org/dc/dcmitype/InteractiveResource" property="dc:title" rel="dc:type">Join - Gerenciador de Cursos</span> by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Francisco Ant&#244;nio da Silva Souza</span> is licensed under a <br />
                <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/2.5/br/" target="_blank">Creative Commons Atribui&#231;&#227;o-Uso N&#227;o-Comercial-Compartilhamento pela mesma Licen&#231;a 2.5 Brasil License</a>.
            {% endblock rodape %}
        </div>
    </div>

</body>
</html>